apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-nginx-app
  template:
    metadata:
      labels:
        app: flask-nginx-app
    spec:
      containers:
      - name: flask-nginx-container
        image: sumesh07/cicd-e2e:latest
        ports:
        - containerPort: 80
